# Generated by Django 5.2.8 on 2026-02-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('keyword_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('keyword_text', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'keyword',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('paper_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('source_type', models.CharField(choices=[('UPLOAD_PDF', 'UPLOAD_PDF'), ('ARXIV_LINK', 'ARXIV_LINK')], max_length=50)),
                ('arxiv_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pdf_file_path', models.CharField(blank=True, max_length=2048, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'paper',
            },
        ),
        migrations.CreateModel(
            name='PaperKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
            options={
                'db_table': 'paper_keyword',
            },
        ),
        migrations.CreateModel(
            name='PaperText',
            fields=[
                ('paper_text_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('raw_text', models.TextField()),
                ('cleaned_text', models.TextField()),
            ],
            options={
                'db_table': 'paper_text',
            },
        ),
    ]
