# Generated by Django 5.2.8 on 2026-02-22 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='papers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paperkeyword',
            name='keyword',
            field=models.ForeignKey(db_column='keyword_id', on_delete=django.db.models.deletion.CASCADE, related_name='keyword_papers', to='papers.keyword'),
        ),
        migrations.AddField(
            model_name='paperkeyword',
            name='paper',
            field=models.ForeignKey(db_column='paper_id', on_delete=django.db.models.deletion.CASCADE, related_name='paper_keywords', to='papers.paper'),
        ),
        migrations.AddField(
            model_name='papertext',
            name='paper',
            field=models.OneToOneField(db_column='paper_id', on_delete=django.db.models.deletion.CASCADE, related_name='text', to='papers.paper'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['user'], name='idx_paper_user_id'),
        ),
        migrations.AddIndex(
            model_name='paperkeyword',
            index=models.Index(fields=['keyword'], name='idx_paper_keyword_keyword'),
        ),
        migrations.AddConstraint(
            model_name='paperkeyword',
            constraint=models.UniqueConstraint(fields=('paper', 'keyword'), name='pk_paper_keyword'),
        ),
    ]
