# Generated by Django 5.2.8 on 2026-04-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_alter_paperkeyword_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperkeyword',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
