# Generated by Django 5.2.8 on 2026-02-22 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('job_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QUEUED', 'QUEUED'), ('PROCESSING', 'PROCESSING'), ('DONE', 'DONE'), ('FAILED', 'FAILED')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analysis_job',
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('result_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('risk_label', models.CharField(blank=True, choices=[('Low', 'Low'), ('Med', 'Med'), ('High', 'High')], max_length=20, null=True)),
                ('explanation_json', models.JSONField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analysis_result',
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('model_version_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=255)),
                ('artifact_path_vectorizer', models.CharField(max_length=2048)),
                ('artifact_path_classifier', models.CharField(max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active_flag', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'model_version',
            },
        ),
    ]
