# Generated by Django 5.2.8 on 2026-02-22 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='job',
            field=models.OneToOneField(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, related_name='result', to='analysis.analysisjob'),
        ),
        migrations.AddConstraint(
            model_name='modelversion',
            constraint=models.UniqueConstraint(condition=models.Q(('active_flag', True)), fields=('active_flag',), name='uq_model_version_one_active'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='model_version',
            field=models.ForeignKey(db_column='model_version_id', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analysis.modelversion'),
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['paper'], name='idx_analysis_job_paper_id'),
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['user'], name='idx_analysis_job_user_id'),
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['status'], name='idx_analysis_job_status'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['model_version'], name='idx_analysis_result_model'),
        ),
    ]
