# Generated by Django 5.2.8 on 2026-02-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('error_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_column='timestamp')),
            ],
            options={
                'db_table': 'error_log',
            },
        ),
    ]
