# Generated by Django 5.2.8 on 2026-02-22 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs_app', '0001_initial'),
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='paper',
            field=models.ForeignKey(blank=True, db_column='paper_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='error_logs', to='papers.paper'),
        ),
    ]
