# Generated by Django 5.2.8 on 2026-02-22 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs_app', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='error_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['user'], name='idx_error_log_user'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['paper'], name='idx_error_log_paper'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['timestamp'], name='idx_error_log_timestamp'),
        ),
    ]
